---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/imdongmin/Documents/cproject/11/project'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C44, symSize: 0x30 }
  - { offsetInCU: 0x4D, offset: 0x4D, size: 0x8, addend: 0x0, symName: _students, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0xB0, offset: 0xB0, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C44, symSize: 0x30 }
  - { offsetInCU: 0xC9, offset: 0xC9, size: 0x8, addend: 0x0, symName: _inputStudentsInfo, symObjAddr: 0x30, symBinAddr: 0x100003C74, symSize: 0x138 }
  - { offsetInCU: 0xFB, offset: 0xFB, size: 0x8, addend: 0x0, symName: _printStudentsInfo, symObjAddr: 0x168, symBinAddr: 0x100003DAC, symSize: 0x118 }
...
